### ISSUE TITLE
Allow inspection of old biscuits

### ISSUE THREAD

**Issue by gaetronik** [biscuit-auth/biscuit-cli#31]
When I try to inspect old crafted biscuit I got 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Format(Version { maximum: 3, minimum: 3, actual: 2 })'
```
I'd like to have a warning and at least datalog output to bake new ones.
Maybe my biscuits are just not rights.
Does it look right to add such a feature ?

**Comment by divarvel** [comment]
Biscuits with the `v2` version tags are based on a bogus spec version and were quickly superseded by a `v3` version tags, so the library has dropped support for them. The simplest solution would be to use an old cli version to inspect them, and more importantly to get rid of them as soon as you can, because they're not supported anywhere now.
